### ISSUE TITLE
Main - доп параметры не удалил

### ISSUE THREAD

**Issue by aademid** [NIBugakov/OCR_frame#1]

**Comment by NIBugakov** [comment]
ну я их осознанно не удалил ,решил такие вещи прям в самом конце удалялть(даже возможно вообще не стоит)
 ,мне вот файналайз понадобился однажды и пришлось его восстанавливать

**Comment by aademid** [comment]
c9e196714254ae2ad06ee2fdf6a7d0d42c420d12
