### ISSUE TITLE
DataExtractor - Тоже с логикой перемудрил

### ISSUE THREAD

**Issue by aademid** [NIBugakov/OCR_frame#19]
207b1d34-978b-4bdb-a2cc-a5cc8b2d9da7

Получение строки... ты можешь это условие вынести в условие цикла, и будет в разы понятнее

**Comment by NIBugakov** [comment]
диопозон от.. вниз

**Comment by aademid** [comment]
f486bd2a76b229e839835f2e03d38c204fd71ebd
